version: '3'
services:
  co-advertisers-api:
    build: .
    container_name: co-advertisers-api
    volumes:
      - .:/home/app
    external_links:
      - actionmedia
    ports:
      - 8055:4000
    environment:
      - BRANCH=dev
      - VIRTUAL_HOST=co-advertisers-api.jatun.systems
    networks:
      - proxy
      - database
    depends_on:
      - redis

  redis:
    image: redis:latest

networks:
  database:
    external: true
  proxy:
    external: true
  default:
    external:
      name: actionmedia-network
